<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_New Client_MuiSkeleton-root MuiSkeleto_da9b63</name>
   <tag></tag>
   <elementGuidId>4a4a59f1-c7b6-4082-87df-527cc1f4173c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div[2]/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.MuiSkeleton-root.MuiSkeleton-rectangular.MuiSkeleton-pulse.css-io6do9</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>78f9f513-9aa1-43e3-959a-f40d489070c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiSkeleton-root MuiSkeleton-rectangular MuiSkeleton-pulse css-io6do9</value>
      <webElementGuid>8795ecab-d37c-4b27-abd3-a796116f9d96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;MuiBox-root css-k008qs&quot;]/div[@class=&quot;MuiBox-root css-cjzos0&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 MuiCard-root css-41i7r2&quot;]/div[@class=&quot;MuiCardContent-root css-1qw96cp&quot;]/div[@class=&quot;MuiBox-root css-0&quot;]/div[@class=&quot;MuiBox-root css-1ebprri&quot;]/span[@class=&quot;MuiSkeleton-root MuiSkeleton-rectangular MuiSkeleton-pulse css-io6do9&quot;]</value>
      <webElementGuid>51a406cb-6878-4d40-93dd-dc6838e4ab17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div[2]/div/span</value>
      <webElementGuid>c6390e4b-ec11-481a-8a69-3f0836b56655</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span</value>
      <webElementGuid>8e24c178-0ac7-49d3-8fa7-da29f8fccc1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
