<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sign InForgot PasswordDont have an acco_798003</name>
   <tag></tag>
   <elementGuidId>1c30dfb6-a7f2-4957-98f6-4254d91613ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-md-6.MuiGrid-grid-lg-5.css-1r63b89</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e54b4ed6-6ba3-46bf-911d-379065775541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12 MuiGrid-grid-md-6 MuiGrid-grid-lg-5 css-1r63b89</value>
      <webElementGuid>173a8660-0bc4-4d45-bf5f-96a966732c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>​​​​Sign InForgot Password?Don't have an account?Sign In With AppleSign In With GoogleorREGISTER</value>
      <webElementGuid>ffc5a3d1-ad62-4deb-b02b-82bf5fb02bdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;MuiGrid-root MuiGrid-container css-kmvksy&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12 MuiGrid-grid-md-6 MuiGrid-grid-lg-5 css-1r63b89&quot;]</value>
      <webElementGuid>3868da3b-0a61-415c-a016-fb366d4a417c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div</value>
      <webElementGuid>c5935783-1f00-4359-aee4-49cae9743462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>c8dde288-f704-4895-aa1b-d425ddbaabbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;​​​​Sign InForgot Password?Don&quot; , &quot;'&quot; , &quot;t have an account?Sign In With AppleSign In With GoogleorREGISTER&quot;) or . = concat(&quot;​​​​Sign InForgot Password?Don&quot; , &quot;'&quot; , &quot;t have an account?Sign In With AppleSign In With GoogleorREGISTER&quot;))]</value>
      <webElementGuid>8d59e808-5382-46d5-aba0-decf0d2f5aa8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
