<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_51025All</name>
   <tag></tag>
   <elementGuidId>d424b74c-d6bd-49c4-b387-d69efa75fade</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id=':ra:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>797f5b76-97e5-4cf8-be48-7f03d3a6c5ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiNativeSelect-select MuiTablePagination-select MuiNativeSelect-standard MuiInputBase-input css-1vynybe</value>
      <webElementGuid>219934ba-cb40-40c5-96a6-4ba73a70cc23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:ra:</value>
      <webElementGuid>8e274b14-d5d1-46bd-90ec-2a5c8543d347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>rows per page</value>
      <webElementGuid>697dd9c4-7082-41c6-9953-e12a3209ef41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>51025All</value>
      <webElementGuid>90c852af-9c7d-409c-8c21-e775763d6ba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:ra:&quot;)</value>
      <webElementGuid>773c2a8d-53ad-41dc-9c24-29d344e5f812</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id=':ra:']</value>
      <webElementGuid>3b9b6889-aee9-4d8b-b402-ef0885ae129c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div[2]/div[4]/td/div/div[2]/select</value>
      <webElementGuid>035832ce-f448-47e7-98b9-123b1cf81f57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 455.000.000'])[1]/following::select[1]</value>
      <webElementGuid>679d9366-348b-4d9f-935c-5208ccc66e78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PajakPerNalA'])[1]/following::select[1]</value>
      <webElementGuid>6537ae1e-a094-4deb-8449-1e2b7b91c043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Restore Items'])[1]/preceding::select[1]</value>
      <webElementGuid>7ed36028-86c3-483c-a9f8-491d5454f39a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WAHUDAAHYAR'])[2]/preceding::select[1]</value>
      <webElementGuid>361a0b0b-e96a-4809-aa58-fc42091712c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>192e7a41-b5f6-4fcb-b2d0-300746318378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = ':ra:' and (text() = '51025All' or . = '51025All')]</value>
      <webElementGuid>3c3709c2-7287-4f5f-882c-2e89014593d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
