<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Tagihan Bulan</name>
   <tag></tag>
   <elementGuidId>df13fc8b-be66-44df-a3cc-e67f90401eac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id=':ri:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c157bbd8-9b46-42de-82af-b8e3956fb909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3a923a87-ddda-45aa-aaf4-87f316f1f97f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:ri:</value>
      <webElementGuid>77e84244-28a9-40cc-a7df-62df1fc9901d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>notes</value>
      <webElementGuid>d51393bc-e602-4377-a047-927a60726a74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>7f20bb15-0c95-4ffe-976d-4ca8c71ec364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiInput-input MuiInputBase-inputMultiline css-10oer18</value>
      <webElementGuid>3662fbe9-9595-4c81-88b4-933c663b3c71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tagihan Bulan</value>
      <webElementGuid>3a45212a-7d8b-472e-ba86-7d93438dde84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:ri:&quot;)</value>
      <webElementGuid>0811b223-e8ea-4124-af8d-a788a7b70133</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id=':ri:']</value>
      <webElementGuid>6d5807b0-d1ac-47cb-a7a7-141384fdf5b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notes'])[1]/following::textarea[1]</value>
      <webElementGuid>a7810671-cd09-4d72-a537-37840bcfa9c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount Paid'])[1]/following::textarea[1]</value>
      <webElementGuid>5a8a4d12-4835-4847-ad77-36d6a998bc0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tagihan Bulan']/parent::*</value>
      <webElementGuid>d85d063a-735a-4c6b-8676-5a3e1aefff3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>54c60317-4e3f-458a-bcfb-4e7446bc46e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = ':ri:' and @name = 'notes' and (text() = 'Tagihan Bulan' or . = 'Tagihan Bulan')]</value>
      <webElementGuid>f422e278-114c-4382-abb4-b74908508e25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
