<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_last_name</name>
   <tag></tag>
   <elementGuidId>cea19d59-f865-459e-997b-e89d3d6316ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;last_name&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>KASIH</value>
      <webElementGuid>b88671a0-c42c-41ae-87d3-506df23c4a76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
