<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_phone_number</name>
   <tag></tag>
   <elementGuidId>0df250f5-d404-4700-88bb-bb72339cc5c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;phone_number&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>81367242096</value>
      <webElementGuid>131c5a98-ec5f-43d1-85fc-64588e653ed7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
