<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Resend link</name>
   <tag></tag>
   <elementGuidId>ed9e3e54-3cbf-4a1a-8586-f7e8535f6cd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;btn-resend&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e7266c20-769d-40d9-9eb3-0b4f9db161b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Password_button__uNqPK</value>
      <webElementGuid>3e915488-795c-4677-96d5-06a2b510e247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Resend link</value>
      <webElementGuid>d99b132e-6807-4296-a8d8-5cafcc33172e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;MuiGrid-root MuiGrid-container css-kmvksy&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12 MuiGrid-grid-md-5 css-3gyv6h&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 css-bqj0tw&quot;]/div[@class=&quot;MuiBox-root css-1ebprri&quot;]/div[1]/div[@class=&quot;Password_buttons__OPcQN&quot;]/button[@class=&quot;Password_button__uNqPK&quot;]</value>
      <webElementGuid>c5ebe8b6-5923-41ce-b3e6-d6d2cddd1429</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div[2]/button[2]</value>
      <webElementGuid>176b7f7e-16b2-430b-933d-818a6e5f54a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back to home'])[1]/following::button[1]</value>
      <webElementGuid>f882f0fd-c7c5-4507-9cc8-2a52a575c011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create invoices professionally anytime and anywhere'])[1]/preceding::button[1]</value>
      <webElementGuid>e8d4861b-e3f2-48fc-88b5-9e0199f7e258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get paid faster with the online payment feature'])[1]/preceding::button[1]</value>
      <webElementGuid>1cf6cb80-85de-4143-8462-af7bd4d21440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Resend link']/parent::*</value>
      <webElementGuid>4086dc13-1826-42c9-9b67-9929b7d04960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>f719733c-501a-4f2e-a0e0-31eb7426e9a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Resend link' or . = 'Resend link')]</value>
      <webElementGuid>da87d14e-2fd3-47bd-8c73-6dafc75eb150</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
